name: Example Workflow
on: workflow_dispatch

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Display Workspace
        run: echo "Workspace is at $GITHUB_WORKSPACE"

      - name: List Files in Workspace
        run: ls $GITHUB_WORKSPACE
